// Code generated by "stringer -type=Prompt"; DO NOT EDIT.

package rline

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Default-0]
	_ = x[Readline-1]
	_ = x[Replxx-2]
}

const _Prompt_name = "DefaultReadlineReplxx"

var _Prompt_index = [...]uint8{0, 7, 15, 21}

func (i Prompt) String() string {
	if i >= Prompt(len(_Prompt_index)-1) {
		return "Prompt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Prompt_name[_Prompt_index[i]:_Prompt_index[i+1]]
}
